Models/ErrorViewModel.cs
namespace rema.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/EstateUnit.cs
using System.ComponentModel.DataAnnotations;

namespace rema.Models;

public class EstateUnit
{
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    public RealEstate RealEstate { get; set; }
}

Models/RealEstate.cs
using System.ComponentModel.DataAnnotations;

namespace rema.Models;

public class RealEstate
{
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    public List<EstateUnit>? EstateUnits { get; set; }
}

Controllers/EstateUnitController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using rema.Data;
using rema.Models;

namespace ream.Controllers;

[Route("real-estates/{realEstateId}/estate-units")]
public class EstateUnitController : Controller
{
  private readonly RemaContext _context;

  public EstateUnitController(RemaContext context)
  {
    _context = context;
  }

  public async Task<IActionResult> Index(int realEstateId)
  {
    var estateUnits = await _context.EstateUnits.ToListAsync();

    return View(estateUnits);
  }

  [HttpGet("new")]
  public IActionResult New(int realEstateId)
  {
    ViewBag.RealEstateId = realEstateId;
    return View();
  }

  [HttpPost("Create")]
  [ValidateAntiForgeryToken]
  public async Task<IActionResult> Create(int realEstateId, [Bind("Name")] EstateUnit estateUnit)
  {
      var realEstate = await _context.RealEstates.FindAsync(realEstateId);
      estateUnit.RealEstate = realEstate;
      ModelState.Clear();
      TryValidateModel(estateUnit);
    if (ModelState.IsValid)
    {
      _context.Add(estateUnit);
      await _context.SaveChangesAsync();
      return RedirectToAction("Index", new { realEstateId });
    }
    return View("New");
  }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using rema.Models;

namespace rema.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/RealEstateController.cs
using Microsoft.AspNetCore.Mvc;
using rema.Models;
using rema.Data;
using Microsoft.EntityFrameworkCore;

namespace rema.Controllers;

[Route("real-estates")]
public class RealEstateController : Controller
{
    private readonly RemaContext _context;

    public RealEstateController(RemaContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index()
    {
        var realEstates = await _context.RealEstates.ToListAsync();
        return View(realEstates);
    }

    [HttpGet("new")]
    public IActionResult New()
    {
        return View();
    }

    [HttpPost("create")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Name")] RealEstate realEstate)
    {
        if (ModelState.IsValid)
        {
            _context.Add(realEstate);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        return View("New");
    }

    [Route("{id}")]
    public async Task<IActionResult> Show(int id)
    {
        var realEstate = await _context.RealEstates.Include(re => re.EstateUnits).AsNoTracking().FirstOrDefaultAsync(re => re.Id == id);

        if (realEstate == null)
        {
            return NotFound();
        }
        return View(realEstate);
    }
}

Views/EstateUnit/Index.cshtml
@model IEnumerable<rema.Models.EstateUnit>

<h1>Estate Units:</h1>
<table>
  <tbody>
    @foreach (var estateUnit in Model)
    {
        <tr>
          <td>
            @estateUnit.Name
          </td>
        </tr>
    }
  </tbody>
</table>

Views/EstateUnit/New.cshtml
@model rema.Models.EstateUnit

<h1>Add new estate unit</h1>

<div class="row">
  <div class="col-md-10">
    <form asp-action="Create" asp-route-realEstateId="@ViewBag.RealEstateId" method="POST">
      <div class="form-group">
          <label asp-for="Name"></label>
          <input asp-for="Name" class="form-control" />
          <span asp-validation-for="Name" class="text-danger"></span>
      </div>
      <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
      </div>
    </form>
  </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/RealEstate/Index.cshtml
@model IEnumerable<rema.Models.RealEstate>

<h1>Real Estates:</h1>

<p>
    <a asp-action="New">Create New Real Estate</a>
</p>

<table>
  <tbody>
    @foreach (var realEstate in Model)
    {
        <tr>
          <td>
            <a asp-action="show" asp-route-id="@realEstate.Id">
              @realEstate.Name
            </a>
          </td>
        </tr>
    }
  </tbody>
</table>

Views/RealEstate/New.cshtml
@model rema.Models.RealEstate

<h1>Add new real estate</h1>

<div class="row">
  <div class="col-md-10">
    <form asp-action="Create">
      <div class="form-group">
          <label asp-for="Name"></label>
          <input asp-for="Name" class="form-control" />
      </div>

      <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
      </div>
  </form>
  </div>
</div>

Views/RealEstate/Show.cshtml
@model rema.Models.RealEstate

<h1>@Model.Name</h1>

<p>
  <a asp-controller="EstateUnit" asp-action="New" asp-route-RealEstateId="@Model.Id">Add Estate Unit</a>
</p>
<p>
  <a asp-controller="EstateUnit" asp-action="Index" asp-route-RealEstateId="@Model.Id">Show Estate Units</a>
</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - rema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/rema.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">rema</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - rema - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>